# Aliases
alias ll='ls -lah --color=auto'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='../../../'
alias .....='../../../../'

alias vi='vim'

alias grep=' grep --color'

alias git='LANG=en_US.UTF-8 git'

alias composer='/usr/local/bin/composer.phar'
